namespace: jonsible
name: iac
description: "Collection to manage my infrastructure"
version: 0.0.1
readme: README.md
authors:
  - "Jonathan Scherrer <jonathan.s.scherrer@gmail.com>"
license_file: 'LICENSE'
repository: https://github.com/jonsible/iac
issues: https://github.com/jonsible/iac/issues

tags: []
dependencies: {}
build_ignore: []
