# code: language=ansible
---
- name: Removing ufw
  become: true
  ansible.builtin.apt:
    name: ufw
    purge: true
    autoremove: true
    state: absent

- name: Set rules (IPv4)
  ansible.builtin.include_tasks:
    file: iptables_rules.yml
  vars:
    rules_ip_version: ipv4

- name: Set rules (IPv6)
  ansible.builtin.include_tasks:
    file: iptables_rules.yml
  vars:
    rules_ip_version: ipv6

- name: Enabling netfilter-persistent
  become: true
  ansible.builtin.systemd:
    name: iptables
    enabled: true
    daemon_reload: true
