#!/bin/bash

create_chain()
{
    chain=$1
    jump=$2
    proto=$3
    if [ "$proto" != "6" ]; then
        iptables -N "$jump" 2> /dev/null
        iptables -C "$chain" -j "$jump" 2> /dev/null || iptables -A "$chain" -j "$jump"
    fi
    if [ "$proto" != "4" ]; then
        ip6tables -N "$jump" 2> /dev/null
        ip6tables -C "$chain" -j "$jump" 2> /dev/null || ip6tables -A "$chain" -j "$jump"
    fi
}
rc=0

create_chain INPUT fw-input
create_chain OUTPUT fw-output
create_chain FORWARD fw-forward

iptables-restore --noflush < /etc/iptables/rules.v4 || rc=1
ip6tables-restore --noflush < /etc/iptables/rules.v6 || rc=1

shopt -s nullglob
for f in /etc/iptables/conf.d/*.v4; do
    iptables-restore --noflush < "$f" || rc=1
done

for f in /etc/iptables/conf.d/*.v6; do
    ip6tables-restore --noflush < "$f" || rc=1
done
shopt -u nullglob

exit $rc
