---
# code: language=ansible
- name: Save iptables
  become: true
  ansible.builtin.shell:
    cmd: |
      iptables-save | grep -vP "^-A (KUBE|FLANNEL)" | grep -vP "^:(KUBE|FLANNEL)" | tee /etc/iptables/rules.v4
      ip6tables-save | grep -vP "^-A (KUBE|FLANNEL)" | grep -vP "^:(KUBE|FLANNEL)" | tee /etc/iptables/rules.v6
  listen: "iptables-save"

- name: Restart iptables
  become: true
  ansible.builtin.command:
    cmd: "netfilter-persistent restart"
  listen: "iptables-restart"

- name: Reload sshd
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
  listen: "sshd-reload"

- name: Restart fail2ban
  become: true
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  listen: "fail2ban-restart"

- name: Reload nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  listen: "nginx-reload"

- name: Apply netplan
  become: true
  ansible.builtin.command:
    cmd: "netplan apply"
  listen: "netplan-apply"

- name: Restart systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  listen: "systemd-networkd-restart"
